export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';

export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
